server:
  port: 8000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/emperwang/springcloudconfig
  application:
    name: config-server-eureka
eureka:
  client:
    service-url:
      defaultZone: http://user:passwd123@localhost:8761/eureka
    healcheck:
      enabled: true
  instance:
    prefer-ip-address: true



