server:
  port: 8007
spring:
  application:
    name: cloud-providerconsul-payment
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: cloud-providerconsul-payment8007
        health-check-critical-timeout: 30m
        prefer-ip-address: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://name2:3306/cloud2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin

mybatis:
  mapper-locations: classpath:mapper/*.xml