server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://user:passwd123@localhost:8761/eureka
spring:
  application:
    name: getway-zuul
# 为多个服务配置路径
zuul:
  routes:
    users1:
      path: /user/**
      serviceId: microservice-provide-user
    users2:
      path: /ribbon/**
      serviceId: consumer-move-ribbon-hystrix


