server:
  port: 8761
security:
  basic:
    enabled: true
  user:
    name: user
    password:  passwd123
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://user:passwd123@localhost:8761/eureka
  instance:
    hostname: localhost




