
server:
  port: 8000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/emperwang/springcloudconfig
security:
  basic:
    enabled: true
  user:
    name: user
    password: passwd123




