server:
  port: 9000
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: microservice-provide-user
logging:
  level:
    root: debug
    com.wk.cloud: debug
    org.hibernate: debug
    org.hibernate.type.descriptor.sql.BasicBinder: Trace
    org.hibernate.type.descriptor.sql.BasicExtractor: Trace
eureka:
  client:
    service-url:
      defaultZone: http://user:passwd123@127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
#    appname: provide-client

