server:
  port: 8005
spring:
  application:
    name: cloud-providerzk-payment
  cloud:
    zookeeper:
      connect-string: name2:2181,name3:2181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://name2:3306/cloud2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin

mybatis:
  mapper-locations: classpath:mapper/*.xml