server:
  port: 9003
#  servlet:
#    context-path: /consumer
eureka:
  client:
    service-url:
      defaultZone: http://user:passwd123@localhost:8761/eureka/
    healcheck:
      enabled: true
  instance:
    appname: consumer-move-ribbon-hystrix
    prefer-ip-address: true
    instance-id: ${eureka.instance.appname}:${spring.cloud.client.ipAddress}:${server.port}
