server:
  port: 8050
eureka:
  client:
    service-url:
      defaultZone: http://user:passwd123@localhost:8761/eureka
spring:
  application:
    name: getway-zuul-fallback
zuul:
  routes:
    microservice-provide-user: /users/**


