server:
  port: 9000
  servlet:
    context-path: /simple
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root: debug
    com.wk.cloud: debug
    org.hibernate: debug
    org.hibernate.type.descriptor.sql.BasicBinder: Trace
    org.hibernate.type.descriptor.sql.BasicExtractor: Trace