server:
  port: 9004
  context-path: /ribbon
eureka:
  client:
    service-url:
      defaultZone: http://user:passwd123@localhost:8761/eureka/
    healcheck:
      enabled: true
  instance:
    appname: consumer-move-ribbon-hystrix-wth-contextpath
    prefer-ip-address: true
    instance-id: ${eureka.instance.appname}:${spring.cloud.client.ipAddress}:${server.port}
    home-page-url-path: /ribbon
