server:
  port: 9002
#  servlet:
#    context-path: /consumer
eureka:
  client:
    service-url:
      defaultZone: http://user:passwd123@localhost:8761/eureka/
    healcheck:
      enabled: true
  instance:
    appname: consumer-move-feign-customizling
    prefer-ip-address: true
    instance-id: ${eureka.instance.appname}:${spring.cloud.client.ipAddress}:${server.port}
logging:
  level:
    com.wk.cloud.microservicesimpleconsumermovie.feign.FeignClient: debug

# 设置hystrix第一次访问的超时时间
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 0.01

# 关闭hystrix第一次访问超时的功能
#hystrix.command.default.execution.timeout.enabled: false

# 关闭feign的hystrix功能
#feign.hystrix.enabled: false