server:
  port: 80
spring:
  application:
    name: consumer-payment-openfeign80
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-7001:7001/eureka
    fetch-registry: true
# 设置ribbon的超时时间
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000

# 配置feign的打印package
logging:
  level:
    com.kai.service.ConsumerPaymentService: debug
